---
# tasks file for my_new_role
- name: Deleiver motd file in the host
  template:
    src: ../templates/motd.j2
    dest: /Users/mohamedhussein/Hussein/ansible/motd
    owner: root
    group: root
    mode: 0444
